### ISSUE TITLE
Proposal: panic on `error` or `warn` on some condition

### ISSUE THREAD

**Issue by vityafx** [daboross/fern#20]
It'd be very nice to `panic!` instead of trying writing something when we are running tests. Could we have an option which specified what to do in `error!` or `warn!` handlers? Panicking in the tests very useful because we may see some problems we may have. Personally I provide two kind of critical functions - one uses `error!` and another one uses `panic!` for showing me why my test fails.

**Comment by daboross** [comment]
We could definitely add this as a log backend, would that work for your use case?

Something like: `Dispatch::new().level(LevelFilter::Warn).chain(fern::Panic);` would panic whenever any warning or higher messages came through. It could then be put as a sub-logger of the main logger, or applied directly.

**Comment by vityafx** [comment]
Thank you!

**Comment by daboross** [comment]
It's no problem, thank you for the suggestion! I wouldn't have thought to add something like this but I can see it being quite useful.
