### ISSUE TITLE
Output to arbitrary Write object

### ISSUE THREAD

**Issue by vorner** [daboross/fern#23]
Hello

I'm looking through logging options available that'd fullfill my use case. Part of it could be done with fern, but there's one small bit lacking. I'd like to plug an arbitrary `Write` object into it.

Would it make sense to add another [`From`](https://docs.rs/fern/*/fern/struct.Output.html#implementations) implementation, accepting `Box<Write>` in addition to all the specific ones? I think it would increase the flexibility.

**Comment by daboross** [comment]
I think this would work!

We could definitely add a `From` for `Box<Write>` and then just have a logging variant which logs to a `Mutex<Box<Write>>` and flushes afterwards. We would also want to add an `Output::raw_write(line_sep)` method to match the other methods allowing setting non-`\n` line separators on things. Documentation could just mention it exists, and suggest wrapping whatever implements Write in a `BufWriter` for better performance than just a raw socket.

I can work on adding this when I have some time in the next few weeks, or if you wanted to submit a PR earlier than that I'd be happy to review.

Thanks for suggesting this!

**Comment by daboross** [comment]
Implemented in 0.5.5. Thanks @vorner!
