### ISSUE TITLE
How to filter different levels for different targets?

### ISSUE THREAD

**Issue by JMurph2015** [daboross/fern#30]
i use fern for logging things in my integration tests.  Lets say I only use one blanket `LevelFilter` for all modules (though this is not the case).  I'd love to be able to send everything `LevelFilter::Info` and above to my log file, then restrict it further to everything `LevelFilter::Warn` and above to send to `STDOUT`.  Is there already a way to do this, and if not, could it be considered as an enhancement?

**Comment by daboross** [comment]
This should be doable by chaining together two `Dispatch` configurations like the following:

```rust
fern::Dispatch::new()
    // other options
    .level(log::LevelFilter::Info)
    .chain(fern::log_file("...")?)
    .chain(
        fern::Dispatch::new()
            .level(log::LevelFilter::Warn)
            .chain(std::io::stdout()),
    )
    .apply()?;
```

This should send all log messages with level 'info' or above to the log file, then send messages which are also above "warn" to stdout.

**Comment by daboross** [comment]
Closing this as I believe this is sufficiently documented by the catch-all-features example at https://docs.rs/fern/0.5.5/fern/struct.Dispatch.html. Feel free to comment, though. I can re-open if needed.

**Comment by JMurph2015** [comment]
@daboross By the way, thanks for the help!  I hadn't gotten around to replying until just now, but it's much appreciated!
