### ISSUE TITLE
The `log_enabled` is sometimes inaccurate.

### ISSUE THREAD

**Issue by vorner** [daboross/fern#38]
Hello

I've managed to get the log_enabled out of sync from what is actually logged in the end (this is a small reproducer, but I've actually hit it in production where it gives me some trouble).

```rust
use log::{debug, info, log_enabled};

fn main() {
    let dummy = fern::Dispatch::new()
        .level(log::LevelFilter::Warn)
        .chain(std::io::stderr());

    let stdout = fern::Dispatch::new()
        .level(log::LevelFilter::Info)
        .level_for("abc", log::LevelFilter::Debug)
        .chain(std::io::stdout());

    fern::Dispatch::new()
        .chain(stdout)
        .chain(dummy)
        .apply()
        .unwrap();

    info!("Hello world");

    debug!("Should not show");

    dbg!(log_enabled!(log::Level::Debug));
}
```

The output is this:

```
Hello world
[src/main.rs:23] log_enabled!(log :: Level :: Debug) = true
```

So, it doesn't log the debug message, but says log is enabled for debug.

Is this on purpose (not chasing through the slave Dispatches because of performance), or just some kind of missed thing?

**Comment by daboross** [comment]
Thanks for finding this!

If this was on purpose, I think that decision was in error. The log crate only calls `Log::enabled` in situations like this where someone's explicitly testing if a log is enabled, so we should definitely recurse into children.

Right now `Dispatch`'s `enabled` implementation is used within `log` as well, and whether it should check children there before calling the formatter is a whole other question. But I would count the behavior when enabled is explicitly queried as a bug.
