### ISSUE TITLE
Add feature for syslog 5

### ISSUE THREAD

**Issue by daboross** [daboross/fern#47]
Should be fairly straightforward, we can do the same thing we did for the syslog3/4 distinction for adding support for syslog 5. Main work is in rewriting full examples to use syslog 5.

There were some things that syslog 3 could do, but syslog 4 couldn't. I can't remember off the top of my head what they were. If syslog 5 fixes these, and is at least as capable as both syslog 3 and 4, we can remove syslog 3/4 examples and leave only actual library code, replacing them entirely with syslog 5 examples.

**Comment by Cogitri** [comment]
I'm looking into this now, but it seems like there aren't too many changes in v4 vs v5, so I think it'd be fine to just drop support for v4.

**Comment by daboross** [comment]
While from a new user's perspective, we probably don't need to support 4.0 (and thus I'd be totally fine dropping all documentation for `syslog-4`), for backwards compatibility, it would be best to keep the feature.

This is the main reason for having the versioned features in the first place - so that we can add new versions without having to release a major version of fern and force everyone to update.

I mean, I would be totally fine with replacing all documentation and examples referencing syslog v4.0 with v5.0, we just still need to keep the feature and support in the codebase for backwards compatibility.

**Comment by Roguelazer** [comment]
syslog 6 is out now.
