### ISSUE TITLE
Catch panics and log them instead of only on stderr

### ISSUE THREAD

**Issue by BlackDex** [daboross/fern#52]
Hello,

It would be nice to also log panics if possible.
Now it seems the panics are only visible on the stderr of the application.
I found something which kinda does this, https://github.com/sfackler/rust-log-panics but if it could be integrated into fern that would be great.

**Comment by daboross** [comment]
I think this is the kind of thing which is best done as a separate integration - it's kind of more on the "consumer" side of the `log` crate than the "backend" side. I'll leave this open for potential future integration, but as a low priority as it is currently possible, and pretty easy (just `log_panics::init()`).

**Comment by BlackDex** [comment]
Yea, i have it integrated now, which is working great.
And since it still uses the default logging, the backtrace now also gets logged to file/syslog/stdout.

**Comment by BlackDex** [comment]
Let's close this. It's been solved for a long time already.
Thx
