### ISSUE TITLE
Any plans for syslog integration?

### ISSUE THREAD

**Issue by tailhook** [daboross/fern#7]
There are two crates `syslog` and `sysly` neither of them integrates either with `log` or `fern`. Any plans on this?

Should syslog logger be in fern? Should it be under feature flag?

**Comment by daboross** [comment]
My apologies for not replying to any of the github issues for over a year ._.

There are no plans at the moment, but it could definitely be done in fern. I haven't had much time to work on rust things due to school, but I'll accept PRs if anyone wants to work on this.

**Comment by daboross** [comment]
This is now supported with fern v0.5.2 under the "syslog-3" feature flag.
